Repository khuyjh/Mobolae-video-reviews-comparison-app, pull requests merged in 2025-09, with the labels that each got.

#63 [HOY-103] feat: 카카오 소셜 로그인 기능 구현 (윤정환)
  src/app/oauth/kakao/page.tsx
  src/app/oauth/signup/kakao/page.tsx
  src/features/auth/api/authApi.ts
  src/features/auth/components/AuthGuard.tsx
  src/features/auth/components/KakaoError.tsx
  src/features/auth/oauth/components/KakaoSignUpForm.tsx
  src/features/auth/schemas/authSchema.ts
  src/features/auth/signIn/components/SocialLogin.tsx
  src/features/auth/types/authTypes.ts
  src/features/auth/utils/moveToKakao.ts
  src/shared/components/LoadingImage.tsx
  src/shared/constants/constants.ts
Labels: 🚀 sprint2, 🎁 Task

#65 [Hoy 4]feat:비교하기 페이지 입력창, 비교하기 버튼 ui 구현(김인)
  src/app/compare/page.tsx
  src/features/compare/components/CompareButton.tsx
  src/features/compare/components/CompareSelect.tsx
Labels: 🚀 sprint2, 🎁 Task

#67 [HOYY-97] feat: Top-Button (일정 높이 스크롤 시 웹 최상단으로 올라가게 해주는 버튼) 구현 (이관현)
  src/app/layout.tsx
  src/shared/components/infinityScroll.tsx
  src/shared/components/scrollToTop.tsx
Labels: 🚀 sprint2, 🧊 Sub-task

#68 [HOY-122] refactor: 카테고리 선택을 링크 기반으로 전환/ 선택 로직을 상태에서 URLSearchParams로 전환 / 카테고리 타입 문자열에서 숫자로 변경 (이유진)
  src/features/mainPage/components/CategoryItem.tsx
  src/features/mainPage/components/CategoryMenu.tsx
  src/features/mainPage/components/CategorySidebar.tsx
  src/features/mainPage/components/MobileCategorySheet.tsx
  src/features/mainPage/services/buildCategoryHref.ts
  src/shared/constants/constants.ts
  src/shared/types/Category.ts
  src/shared/types/CategoryTypes.ts
  src/shared/types/categoryTypes.ts
Labels: 🚀 sprint2, 🎁 Task

#71 [HOY-127] feat: 토스트 구현 (이관현)
  package-lock.json
  package.json
  src/app/layout.tsx
  src/app/toast/page.tsx
  src/shared/components/toastProvider.tsx
  src/styles/globals.css
Labels: 🚀 sprint2, 🎁 Task

#73 [HOY-126] feat: 콘텐츠 리스트 구현 및 필터·정렬 기능 추가
  src/app/page.tsx
  src/app/product/[productid]/page.tsx
  src/features/mainPage/components/ContentList.tsx
  src/features/mainPage/components/MostReviewed.tsx
  src/features/mainPage/components/ReviewerRanking.tsx
  src/features/mainPage/components/TopShowcase.tsx
  src/features/mainPage/mock/contents.ts
  src/features/mainPage/mock/mockContents.ts
  src/shared/types/content.ts
  src/shared/utils/filterContents.ts
  src/shared/utils/mapApiToItem.ts
  src/shared/utils/query.ts
  src/shared/utils/sortContents.ts
Labels: 🚀 sprint2, 🎁 Task

#74 [Hoy-21] feat: 비교하기 페이지 결과창 및 문구 ui 제작(김인)
  src/app/compare/page.tsx
  src/features/compare/components/CompareButton.tsx
  src/features/compare/components/CompareResult.tsx
  src/features/compare/components/CompareResultSummary.tsx
  src/features/compare/components/CompareResultTable.tsx
  src/features/compare/components/CompareSelect.tsx
  src/features/compare/lib/compareCalc.ts
  src/features/compare/model/useCompareStore.ts
  src/features/compare/types/compareMockTypes.ts
  src/features/compare/types/compareTypes.ts
Labels: 🚀 sprint2, 🎁 Task

#72 [HOY-128] feat: 리다이렉트 모달 제작 및 사이트 리다이렉트 로직 구현 (윤정환)
  src/app/oauth/kakao/page.tsx
  src/app/oauth/signup/kakao/page.tsx
  src/app/signin/page.tsx
  src/app/signup/page.tsx
  src/features/auth/components/AuthGuard.tsx
  src/features/auth/components/RedirectModal.tsx
  src/features/auth/oauth/components/KakaoSignUpForm.tsx
  src/features/auth/signIn/components/SignInForm.tsx
  src/features/auth/signIn/components/SocialLogin.tsx
  src/features/auth/signUp/components/SignUpForm.tsx
  src/features/auth/utils/moveToKakao.ts
  src/shared/components/GlobalNav.tsx
Labels: 🚀 sprint2, 🎁 Task

#81 [Hoy 23] fix: 홈, 프로필 아이템 카드 이미지 테두리에 rounded-lg적용(김인)
  src/shared/components/HomeItemCard.tsx
Labels: 🚀 sprint1, 🎁 Task

#82 [HOY-139] fix : 2차 QA 메인페이지 피드백 반영 (이유진)
  src/app/page.tsx
  src/features/mainPage/components/ArrowList.tsx
  src/features/mainPage/components/CategoryItem.tsx
  src/features/mainPage/components/CategorySidebar.tsx
  src/features/mainPage/components/FloatingButton.tsx
  src/features/mainPage/components/MobileCategorySheet.tsx
  src/features/mainPage/components/ReviewerRanking.tsx
  src/shared/components/MobileGnbSheet.tsx
Labels: 🚀 sprint2, 🎁 Task

#77 [HOY-21] fix: 비교하기 페이지동일 비교 불가 수정, 모바일 반응형 수정(김인)
  src/app/compare/page.tsx
  src/features/compare/components/CompareButton.tsx
  src/features/compare/components/CompareResult.tsx
  src/features/compare/components/CompareResultSummary.tsx
  src/features/compare/components/CompareSelect.tsx
  src/features/compare/model/useCompareStore.ts
Labels: 🚀 sprint2, 🎁 Task

#87 codegen활용 tanstack query hook 생성
  openapi/queries/common.ts
  openapi/queries/ensureQueryData.ts
  openapi/queries/index.ts
  openapi/queries/infiniteQueries.ts
  openapi/queries/prefetch.ts
  openapi/queries/queries.ts
  openapi/queries/suspense.ts
  openapi/requests/index.ts
  openapi/requests/schemas.gen.ts
  openapi/requests/services.gen.ts
  openapi/requests/types.gen.ts
  package-lock.json
  package.json
  src/features/auth/api/authApi.ts
  src/shared/api/apiClients.ts
  src/shared/constants/constants.ts
Labels: 🚀 sprint2

#83 [HOY-34] 콘텐츠 상세 정보 수정 모달 & 삭제 확인 모달 UI 구현 (이관현)
  src/features/product/components/productCard/productButtons.tsx
  src/features/product/components/productCard/productCard.tsx
  src/features/product/components/productModal/editDeleteModal.tsx
  src/features/product/components/productModal/reviewAddModal.tsx
  src/shared/components/deleteConfirmModal.tsx
  src/shared/components/imageUploader.tsx
  src/shared/components/textAreaWithCounter.tsx
  src/shared/components/toastProvider.tsx
Labels: 🚀 sprint2, 🎁 Task

#84 [Hoy 140] feat: 비교 콘텐츠 전역 상태 관리화(김인)
  src/app/compare/page.tsx
  src/features/compare/components/CompareButton.tsx
  src/features/compare/components/CompareResult.tsx
  src/features/compare/model/useCompareStore.ts
  src/features/compare/types/compareTypes.ts
  src/shared/stores/useCompareStore.ts
Labels: 🚀 sprint2, 🎁 Task

#95 [HOY-31] refactor: 상세페이지 SSR/CSR 분리 (이관현)
  src/app/product/[productid]/page.tsx
  src/app/products/[productId]/page.tsx
  src/features/product/components/productCard/productHeader.tsx
  src/features/products/components/productCard/productButtons.tsx
  src/features/products/components/productCard/productCard.tsx
  src/features/products/components/productCard/productDescription.tsx
  src/features/products/components/productCard/productHeader.tsx
  src/features/products/components/productDetailsPageClient.tsx
  src/features/products/components/productModal/compareAddedModal.tsx
  src/features/products/components/productModal/compareReadyModal.tsx
  src/features/products/components/productModal/compareReplaceDoneModal.tsx
  src/features/products/components/productModal/compareReplaceSelectModal.tsx
  src/features/products/components/productModal/editDeleteModal.tsx
  src/features/products/components/productModal/index.tsx
  src/features/products/components/productModal/reviewModal.tsx
  src/features/products/components/reviewCard/reviewCard.tsx
  src/features/products/components/reviewCard/reviewDescription.tsx
  src/features/products/components/reviewCard/reviewMeta.tsx
  src/features/products/components/reviewCard/reviewUser.tsx
  src/features/products/components/reviewSortDropdown.tsx
  src/features/products/components/statisticsCard.tsx
Labels: 🚀 sprint3, 🎁 Task

#94 [Hoy 134] feat: 비교하기 페이지 api 연결 작업(김인)
  src/app/compare/page.tsx
  src/features/compare/components/CompareResult.tsx
  src/features/compare/components/CompareSelect.tsx
  src/features/compare/types/compareMockTypes.ts
  src/features/compare/types/compareTypes.ts
  src/features/compare/utils/contentMapper.ts
Labels: 🚀 sprint3, 🎁 Task

#93 [HOY-138]feat: 콘텐츠 추가 모달 구현 (이유진)
  src/features/mainPage/components/AddContentModal.tsx
  src/features/mainPage/components/FloatingButton.tsx
  src/features/mainPage/components/NameDuplicateGuideInput.tsx
  src/features/mainPage/hooks/useProductNameSearch.ts
  src/features/mainPage/services/productForm.schema.ts
  src/shared/utils/normalize.ts
Labels: 🚀 sprint3, 🎁 Task

#98 [HOY-115] feat: floating button 비로그인 유저 리다이렉트 모달 로직 구현 및 fallback 이미지 추가, 리스트 순서 수정 (이유진)
  public/images/FallbackImg.png
  src/app/page.tsx
  src/features/mainPage/components/FloatingButton.tsx
  src/features/mainPage/components/MostReviewed.tsx
  src/features/mainPage/components/TopRated.tsx
Labels: 🚀 sprint3, 🎁 Task

#105 [HOY-149] feat: 프로필 수정 모달 제작, SafeProfileImg 컴포넌트 제작, 로그아웃 추가, TextArea 컴포넌트 수정, Authguard 권한 재설정 로직 수정 (윤정환)
  public/images/ProfileFallbackImg.png
  src/app/mypage/page.tsx
  src/features/auth/components/AuthGuard.tsx
  src/features/mypage/components/ProfileCard.tsx
  src/features/mypage/components/ProfileUpdateForm.tsx
  src/features/mypage/components/ProfileUpdateModal.tsx
  src/features/mypage/schemas/profileSchema.ts
  src/shared/components/SafeProfileImage.tsx
  src/shared/components/textAreaWithCounter.tsx
  src/shared/stores/userStore.ts
  src/shared/types/userTypes.ts
  src/styles/globals.css
Labels: 🚀 sprint3, 🎁 Task, 🕷️ Bug

#102 [HOY-162] fix:비교 입력창 입력 오류 수정(김인)
  src/features/compare/components/CompareSelect.tsx
Labels: 🚀 sprint3, 🕷️ Bug

#108 [Hoy 165] fix: 모달에서 비교 교체 가능 수정 및 안전 초기화 추가(김인)
  src/features/mainPage/components/FloatingButton.tsx
  src/shared/stores/useCompareStore.ts
Labels: 🚀 sprint3, 🎁 Task

#110 [HOY-123] feat: reviewer ranking api연결 및 동률 처리, UI/UX 개선 (이유진)
  src/features/mainPage/components/ReviewerRanking.tsx
  src/shared/types/reviewer.ts
  src/shared/utils/reviewerMapper.ts
  src/shared/utils/reviewerSort.ts
Labels: 🚀 sprint3, 🧊 Sub-task

#111 [HOY-167] feat: GNB 검색 기능 추가 (이유진)
  src/features/mainPage/components/ContentList.tsx
  src/shared/components/GlobalNav.tsx
Labels: 🚀 sprint3, 🎁 Task

#123 [HOY-175] feat: 상세 페이지 동적 metadata설정 및 ogimage 추가 (윤정환)
  public/icons/favicon.ico
  public/images/OGImg.png
  src/app/layout.tsx
  src/app/products/[productId]/page.tsx
  src/shared/constants/metadata.ts
  src/shared/utils/getMetadata.ts
Labels: 🚀 sprint3, 🎁 Task

#120 [Hoy-171] fix: (QA 수정 사항) 유저 전환 시 로컬스토리지 제대로 반영 안되던 문제 수정(김인)
  src/features/compare/components/CompareSelect.tsx
  src/features/compare/types/compareTypes.ts
  src/shared/stores/useCompareStore.ts
  src/shared/stores/userIdSource.ts
Labels: 🚀 sprint3, 🕷️ Bug

#126 [HOY-173] fix: 상세 페이지 3차 QA 피드백 반영 (이관현)
  src/app/products/[productId]/page.tsx
  src/app/toast/page.tsx
  src/features/mypage/components/activityCard.tsx
  src/features/products/components/productCard/productButtons.tsx
  src/features/products/components/productCard/productCard.tsx
  src/features/products/components/productCard/productHeader.tsx
  src/features/products/components/productDetailsPageClient.tsx
  src/features/products/components/productModal/editDeleteModal.tsx
  src/features/products/components/productModal/reviewModal.tsx
  src/features/products/components/reviewCard/reviewCard.tsx
  src/features/products/components/reviewCard/reviewUser.tsx
  src/features/products/components/statisticsCard.tsx
  src/features/products/components/virtualizedInfinityScroll.tsx
  src/shared/components/card/avatarCard.tsx
  src/shared/components/imageUploader.tsx
  src/shared/constants/constants.ts
  src/shared/lib/kakaoShare.ts
Labels: 🚀 sprint3, 🎁 Task

#124 [HOY-132] feat: 탭 리스트 api 연결 / 무한스크롤 적용/ 마이페이지 오류 수정 (배혜민)
  src/app/mypage/page.tsx
  src/app/user/[userId]/page.tsx
  src/features/mypage/components/ProfileTabsSection.tsx
  src/shared/utils/mapToContentItem.ts
Labels: 🚀 sprint3, 🎁 Task

#129 [HOY-151] feat: skeleton UI 적용
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/app/user/[userId]/page.tsx
  src/features/compare/components/CompareResult.tsx
  src/features/mainPage/components/ReviewerRanking.tsx
  src/features/mainPage/components/VirtualizedContentGrid.tsx
  src/features/mainPage/hooks/useMinHold.tsx
  src/shared/components/GlobalNav.tsx
  src/shared/components/SafeImage.tsx
  src/shared/components/SafeProfileImage.tsx
  src/shared/components/skeleton/CompareResultSkeleton.tsx
  src/shared/components/skeleton/FullGridSkeleton.tsx
  src/shared/components/skeleton/HomeItemCardSkeleton.tsx
  src/shared/components/skeleton/PofilePageSkeleton.tsx
  src/shared/components/skeleton/ReviewSkeleton.tsx
  src/shared/components/skeleton/ReviewerRankingSkeleton.tsx
  src/shared/components/skeleton/Skeleton.tsx
Labels: 🚀 sprint3, 🎁 Task

#131 [HOY-179] feat: 리뷰 없을 때 문구 & 토스트 중복 방지 처리 & 이미지 크기 조절 (이관현)
  src/features/products/components/productCard/productCard.tsx
  src/features/products/components/productCard/productHeader.tsx
  src/features/products/components/productDetailsPageClient.tsx
  src/features/products/components/productModal/editDeleteModal.tsx
  src/features/products/components/productModal/reviewModal.tsx
  src/features/products/components/statisticsCard.tsx
  src/shared/utils/compareModalUtils.ts
Labels: 🚀 sprint3, 🎁 Task

#132 [Hoy-152] refactor: mainpage detail - 홈 쿼리 정규화, 빈/에러 상태 UI 추가, 토스트 UX 개선, 마이너 리팩토링 (이유진)
  src/app/page.tsx
  src/features/mainPage/components/AddContentModal.tsx
  src/features/mainPage/components/CategoryItem.tsx
  src/features/mainPage/components/ContentEmpty.tsx
  src/features/mainPage/components/ContentList.tsx
  src/features/mainPage/components/HomeQueryGuard.tsx
  src/features/mainPage/components/ReviewerRanking.tsx
  src/features/mainPage/mock/mockContents.ts
  src/features/mainPage/services/queryNorm.ts
Labels: 🚀 sprint3, 🎁 Task

#133 [HOY-159] feat: splash 화면 추가 및 404 페이지 추가, 로딩 컴포넌트 아이콘,스타일 수정
  package-lock.json
  package.json
  public/icons/LoadingIcon.svg
  public/icons/LogoIcon.png
  public/images/404.png
  public/lotties/splash.json
  src/app/not-found.tsx
  src/features/mainPage/components/ReviewerRanking.tsx
  src/shared/components/LoadingImage.tsx
  src/shared/components/Splash.tsx
Labels: 🚀 sprint3, 🎁 Task

#147 [Hoy-190] fix: 폰트 파일 woff2 파일로 교체 및 preload: false 적용(김인)
  package-lock.json
  package.json
  public/fonts/Pretendard-Bold.woff
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-Light.woff
  public/fonts/Pretendard-Light.woff2
  public/fonts/Pretendard-Medium.woff
  public/fonts/Pretendard-Medium.woff2
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.woff
  public/fonts/Pretendard-SemiBold.woff2
  src/app/layout.tsx
Labels: 🎁 Task, 🚀 sprint4

#153 [Hoy-190] fix: woff2 호환 안되는 상황 대비 fallback 처리 및 폰트 파일 정리(김인)
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-Light.woff2
  public/fonts/Pretendard-Medium.woff2
  public/fonts/Pretendard-Regular.woff
  public/fonts/Pretendard-SemiBold.woff
  src/app/layout.tsx
Labels: 🎁 Task, 🚀 sprint4

#152 [HOY-191] 코드 주석 추가 / 코드 개선 (배혜민)
  src/app/mypage/page.tsx
  src/app/user/[userId]/page.tsx
  src/features/mypage/components/ProfileCard.tsx
  src/features/mypage/components/ProfileModal/FollowModal.tsx
  src/features/mypage/components/ProfileTabsSection.tsx
  src/features/user/hooks/useFollowMutaion.ts
Labels: 🧊 Sub-task, 🚀 sprint4

#156 [HOY-193] fix: 상세 페이지 dynamic import 적용 (이관현)
  src/features/products/components/productCard/productCard.tsx
  src/features/products/components/reviewCard/reviewCard.tsx
Labels: 🎁 Task, 🚀 sprint4

#160 [HOY-200] fix: 성능 개선 (배혜민)
  src/app/mypage/page.tsx
  src/app/user/[userId]/page.tsx
  src/features/mypage/components/ProfileCard.tsx
  src/features/mypage/components/ProfileTabs.tsx
Labels: 🧊 Sub-task, 🚀 sprint4
