Repository khuyjh/Mobolae-video-reviews-comparison-app, pull requests merged in 2025-08, with the labels that each got.

#14 [HOY-25] feat: 공용 버튼 컴포넌트 제작 (윤정환)
  src/shared/components/Button.tsx
  src/shared/components/test.txt
Labels: 🚀 sprint1, 🎁 Task

#22 [HOY-14]feat: floating button 컴포넌트 구현 - 기본 UI (이유진)
  src/app/page.tsx
  src/features/mainPage/components/CategoryItem.tsx
  src/features/mainPage/components/CategoryMenu.tsx
  src/features/mainPage/components/CategorySidebar.tsx
  src/features/mainPage/components/FloatingButton.tsx
  src/features/test.txt
Labels: 🚀 sprint1, 🎁 Task

#26 main 배포 병합
  components.json
  next.config.ts
  package-lock.json
  package.json
  public/icons/VisibilityOffIcon.svg
  public/icons/VisibilityOnIcon.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/features/mainPage/components/CategoryItem.tsx
  src/features/mainPage/components/CategoryMenu.tsx
  src/features/mainPage/components/CategorySidebar.tsx
  src/features/mainPage/components/FloatingButton.tsx
  src/features/test.txt
  src/shared/components/Button.tsx
  src/shared/components/Dropdown.tsx
  src/shared/components/Input.tsx
  src/shared/components/PasswordInput.tsx
  src/shared/components/card/statisticsCard.tsx
  src/shared/components/chip.tsx
  src/shared/components/test.txt
  src/shared/components/ui/select.tsx
  src/shared/constants/constants.ts
  src/shared/lib/cn.ts
  src/shared/lib/test.txt
  src/shared/providers/QueryProvider.tsx
  src/shared/types/CategoryTypes.ts
  src/shared/types/test.txt
  src/shared/utils/formatters.ts
  src/shared/utils/test.txt
  src/styles/globals.css
  svg.d.ts
  tailwind.config.ts
Labels: 🚀 sprint1

#31 [Hoy 23]feat: 홈, 프로필 화면 아이템 카드 컴포넌트 제작(김인)
  public/images/testImage.png
  src/shared/components/HomeItemCard.tsx
Labels: 🚀 sprint1, 🧊 Sub-task

#34 [HOY-22] feat: GlobalNav 컴포넌트 및 아이콘 추가 (배혜민)
  public/icons/Logo.svg
  public/icons/MenuIcon.svg
  public/icons/SearchIcon.svg
  src/app/layout.tsx
  src/app/mypage/page.tsx
  src/shared/components/GlobalNav.tsx
  src/shared/components/card/ranking.tsx
Labels: 🚀 sprint1, 🎁 Task

#43 [HOY-110] fix: 공용 버튼 호버 색상 추가, 회원가입 페이지 모바일 뷰 버튼 여백 조정 (윤정환)
  src/features/auth/signUp/components/SignUpForm.tsx
  src/shared/components/Button.tsx
Labels: 🚀 sprint1

#44 [HOY-102] feat: 로그인 페이지 폼 연동 및 api 연결 (윤정환)
  src/features/auth/api/authApi.ts
  src/features/auth/schemas/authSchema.ts
  src/features/auth/signIn/components/SignInForm.tsx
  src/features/auth/types/authTypes.ts
Labels: 🚀 sprint1, 🎁 Task

#40 [HOY-9]fix:드롭다운 w값 QA 수정사항 반영(김인)
  src/shared/components/Dropdown.tsx
Labels: 🚀 sprint1, 🎁 Task

#48 [HOY-28] feat: 콘텐츠 상세 카드 컴포넌트 구현 (이관현)
  public/icons/kakaotalk.svg
  public/icons/share.svg
  src/shared/components/card/productCard/productButtons.tsx
  src/shared/components/card/productCard/productCard.tsx
  src/shared/components/card/productCard/productDescription.tsx
  src/shared/components/card/productCard/productHeader.tsx
Labels: 🚀 sprint1, 🧊 Sub-task

#52 [HOY-26] [HOY-27] refactor: 통계 카드, 활동 카드 1차 QA 반영 및 단일 페이지 전용 컴포넌트로 변경 (이관현)
  src/shared/components/card/activityCard.tsx
  src/shared/components/card/statisticsCard.tsx
Labels: 🚀 sprint1, 🧊 Sub-task

#51 [HOY-59]feat: 메인 페이지 레이아웃 1차 구축 및 페이지 내부 필요한 컴포넌트들 생성 (이유진)
  next.config.ts
  src/app/page.tsx
  src/features/mainPage/components/CategorySidebar.tsx
  src/features/mainPage/components/ContentGrid.tsx
  src/features/mainPage/components/MobileCategorySheet.tsx
  src/features/mainPage/components/MostReviewed.tsx
  src/features/mainPage/components/ReviewerRanking.tsx
  src/features/mainPage/components/TopShowcase.tsx
  src/features/mainPage/mock/contents.ts
  src/shared/types/content.ts
Labels: 🚀 sprint1, 🎁 Task

#54 [HOY-106][HOY-108] feat: 토큰관리 로직 및 유저 상태 관리 로직 구현 (윤정환)
  package-lock.json
  package.json
  src/app/layout.tsx
  src/features/auth/api/authApi.ts
  src/features/auth/components/AuthGuard.tsx
  src/features/auth/signIn/components/SignInForm.tsx
  src/features/auth/signUp/components/SignUpForm.tsx
  src/features/auth/types/authTypes.ts
  src/features/auth/utils/cookie.ts
  src/shared/api/apiClients.ts
  src/shared/components/GlobalNav.tsx
  src/shared/stores/test.txt
  src/shared/stores/userStore.ts
  src/shared/types/userTypes.ts
Labels: 🚀 sprint2, 🎁 Task

#53 [HOY-24] feature: 아바타 카드 컴포넌트 추가 (배혜민)
  public/images/profileImg.jpg
  src/app/mypage/page.tsx
  src/shared/components/card/avatarCard.tsx
  src/shared/components/chip.tsx
Labels: 🚀 sprint1, 🧊 Sub-task

#55 [HOY-119] feat: 로딩 컴포넌트 제작 (윤정환)
  public/icons/LoadingIcon.svg
  src/features/auth/components/AuthGuard.tsx
  src/shared/components/LoadingImage.tsx
  src/styles/globals.css
Labels: 🚀 sprint2, 🎁 Task

#56 [HOY-120] feat: fetch api 인스턴스 제작 (윤정환)
  src/shared/api/apiClients.ts
  src/shared/api/serverApi.ts
  src/shared/constants/constants.ts
Labels: 🚀 sprint2, 🎁 Task

#58 [HOY-121] chore: globals.css 색상 변경 및 Button, Input 컴포넌트 스타일 수정
  src/shared/components/Button.tsx
  src/shared/components/Input.tsx
  src/styles/globals.css
Labels: 🚀 sprint2, 🎁 Task

#57 [HOY-29] 리뷰 카드 컴포넌트 구현 (이관현)
  src/features/product/ReviewCard.tsx
  src/features/product/ReviewDescription.tsx
  src/features/product/ReviewMeta.tsx
  src/features/product/ReviewUser.tsx
  src/shared/utils/formatDate.ts
Labels: 🚀 sprint1, 🧊 Sub-task

#60 [HOY-64] feat: 프로필 카드 구현 (배혜민)
  src/app/mypage/page.tsx
  src/features/mypage/components/ProfileCard.tsx
Labels: 🚀 sprint1, 🎁 Task
